### ISSUE TITLE
Version: 2612

### ISSUE THREAD

**Issue by deontae-smith** [alexguirre/RAGENativeUI#142]
Hello,
My game updated to 2612 however currently RAGE supports 2545.
Will there be an update to this file to support the new version?

**Comment by kklzz19820927** [comment]
4/30/2022 5:02:33 AM.566] LSPD First Response: ------------------------------
[4/30/2022 5:02:33 AM.566] LSPD First Response: Inner exceptions:
[4/30/2022 5:02:33 AM.567] LSPD First Response: ------------------------------
[4/30/2022 5:02:33 AM.567] LSPD First Response: Stack trace:
[4/30/2022 5:02:33 AM.567] LSPD First Response: at Rage.Native.NativeFunction.CallByAddress(IntPtr address, Type returnType, NativeArgument[] arguments)
[4/30/2022 5:02:33 AM.567] at Rage.Native.NativeFunction.CallByHash(UInt64 nativeHash, Type returnType, NativeArgument[] arguments)
[4/30/2022 5:02:33 AM.567] at Rage.Native.NativeFunction.CallByHash[ReturnType](UInt64 nativeHash, NativeArgument[] arguments)
[4/30/2022 5:02:33 AM.567] at sZagknivDJGcrpVGCIspDPKkBGBMA.crhnxyHpEwVkmrwOYgJkBHotQfHB()
[4/30/2022 5:02:33 AM.567] at sZagknivDJGcrpVGCIspDPKkBGBMA.OzNAbRKKFQBamPyQqMRPYewKkSBk()
[4/30/2022 5:02:33 AM.567] at Rage.GameFiber.Main()

**Comment by da-mentl-1** [comment]
Im also having same issues with my game.  It updated to 2612 however currently RAGE supports 2545.
Will there be an update to this file to support the new version?

**Comment by pnwparksfan** [comment]
RageNativeUI works fine on 2612. You need to update RagePluginHook which is a separate mod. It's available in the [manual install download of LSPDFR](https://www.lcpdfr.com/downloads/gta5mods/g17media/7792-lspd-first-response/).

**Comment by kklzz19820927** [comment]
> RageNativeUI works fine on 2612. You need to update RagePluginHook which is a separate mod. It's available in the [manual install download of LSPDFR](https://www.lcpdfr.com/downloads/gta5mods/g17media/7792-lspd-first-response/).

I have installed the latest version, but it still prompts an error
