### ISSUE TITLE
Bug: Embedded texture features cause game crash in v2802

### ISSUE THREAD

**Issue by pnwparksfan** [alexguirre/RAGENativeUI#155]
On RNUI 1.9.1 on GTA V 2802, using embedded textures with the `embed:` prefix causes a game crash when trying to retrieve the texture dimensions: 

```
[1/31/2023 10:29:56 PM.676] RAGENativeUI Examples: ==============================
[1/31/2023 10:29:56 PM.677] RAGENativeUI Examples: UNHANDLED EXCEPTION DURING GAME FIBER TICK
[1/31/2023 10:29:56 PM.677] RAGENativeUI Examples: ------------------------------
[1/31/2023 10:29:56 PM.678] RAGENativeUI Examples: Origin: Game fiber "<UNNAMED THREAD>".
[1/31/2023 10:29:56 PM.678] RAGENativeUI Examples: ------------------------------
[1/31/2023 10:29:56 PM.680] RAGENativeUI Examples: Exception type: System.AccessViolationException
[1/31/2023 10:29:56 PM.682] RAGENativeUI Examples: Exception message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[1/31/2023 10:29:56 PM.683] RAGENativeUI Examples: ------------------------------
[1/31/2023 10:29:56 PM.683] RAGENativeUI Examples: Inner exceptions:
[1/31/2023 10:29:56 PM.685] RAGENativeUI Examples: ------------------------------
[1/31/2023 10:29:56 PM.685] RAGENativeUI Examples: Stack trace:
[1/31/2023 10:29:56 PM.686] RAGENativeUI Examples: at Rage.Native.NativeFunction.CallByAddress(IntPtr address, Type returnType, NativeArgument[] arguments)
[1/31/2023 10:29:56 PM.686] at Rage.Native.DynamicNativeFunction.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
[1/31/2023 10:29:56 PM.687] at CallSite.Target(Closure , CallSite , Object , String , String )
[1/31/2023 10:29:56 PM.687] at RAGENativeUI.N.GetTextureResolution(String textureDict, String textureName)
[1/31/2023 10:29:56 PM.688] at RAGENativeUI.PauseMenu.MissionLogo.get_Resolution()
[1/31/2023 10:29:56 PM.689] at RAGENativeUI.PauseMenu.MissionLogo.get_IsTextureLoaded()
[1/31/2023 10:29:56 PM.689] at RAGENativeUI.PauseMenu.TabMissionSelectItem.Draw()
[1/31/2023 10:29:56 PM.689] at RAGENativeUI.PauseMenu.TabView.Update()
[1/31/2023 10:29:56 PM.690] at RNUIExamples.PauseMenuExample.ProcessMenus()
[1/31/2023 10:29:56 PM.691] at Rage.GameFiber.Main()
[1/31/2023 10:29:56 PM.691] RAGENativeUI Examples: ==============================
```

**Comment by philippe53** [comment]
> On RNUI 1.9.1 on GTA V 2802, using embedded textures with the `embed:` prefix causes a game crash when trying to retrieve the texture dimensions:
> 
> ```
> [1/31/2023 10:29:56 PM.676] RAGENativeUI Examples: ==============================
> [1/31/2023 10:29:56 PM.677] RAGENativeUI Examples: UNHANDLED EXCEPTION DURING GAME FIBER TICK
> [1/31/2023 10:29:56 PM.677] RAGENativeUI Examples: ------------------------------
> [1/31/2023 10:29:56 PM.678] RAGENativeUI Examples: Origin: Game fiber "<UNNAMED THREAD>".
> [1/31/2023 10:29:56 PM.678] RAGENativeUI Examples: ------------------------------
> [1/31/2023 10:29:56 PM.680] RAGENativeUI Examples: Exception type: System.AccessViolationException
> [1/31/2023 10:29:56 PM.682] RAGENativeUI Examples: Exception message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
> [1/31/2023 10:29:56 PM.683] RAGENativeUI Examples: ------------------------------
> [1/31/2023 10:29:56 PM.683] RAGENativeUI Examples: Inner exceptions:
> [1/31/2023 10:29:56 PM.685] RAGENativeUI Examples: ------------------------------
> [1/31/2023 10:29:56 PM.685] RAGENativeUI Examples: Stack trace:
> [1/31/2023 10:29:56 PM.686] RAGENativeUI Examples: at Rage.Native.NativeFunction.CallByAddress(IntPtr address, Type returnType, NativeArgument[] arguments)
> [1/31/2023 10:29:56 PM.686] at Rage.Native.DynamicNativeFunction.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
> [1/31/2023 10:29:56 PM.687] at CallSite.Target(Closure , CallSite , Object , String , String )
> [1/31/2023 10:29:56 PM.687] at RAGENativeUI.N.GetTextureResolution(String textureDict, String textureName)
> [1/31/2023 10:29:56 PM.688] at RAGENativeUI.PauseMenu.MissionLogo.get_Resolution()
> [1/31/2023 10:29:56 PM.689] at RAGENativeUI.PauseMenu.MissionLogo.get_IsTextureLoaded()
> [1/31/2023 10:29:56 PM.689] at RAGENativeUI.PauseMenu.TabMissionSelectItem.Draw()
> [1/31/2023 10:29:56 PM.689] at RAGENativeUI.PauseMenu.TabView.Update()
> [1/31/2023 10:29:56 PM.690] at RNUIExamples.PauseMenuExample.ProcessMenus()
> [1/31/2023 10:29:56 PM.691] at Rage.GameFiber.Main()
> [1/31/2023 10:29:56 PM.691] RAGENativeUI Examples: ==============================
> ```

**Comment by philippe53** [comment]
> On RNUI 1.9.1 on GTA V 2802, using embedded textures with the `embed:` prefix causes a game crash when trying to retrieve the texture dimensions:
> 
> ```
> [1/31/2023 10:29:56 PM.676] RAGENativeUI Examples: ==============================
> [1/31/2023 10:29:56 PM.677] RAGENativeUI Examples: UNHANDLED EXCEPTION DURING GAME FIBER TICK
> [1/31/2023 10:29:56 PM.677] RAGENativeUI Examples: ------------------------------
> [1/31/2023 10:29:56 PM.678] RAGENativeUI Examples: Origin: Game fiber "<UNNAMED THREAD>".
> [1/31/2023 10:29:56 PM.678] RAGENativeUI Examples: ------------------------------
> [1/31/2023 10:29:56 PM.680] RAGENativeUI Examples: Exception type: System.AccessViolationException
> [1/31/2023 10:29:56 PM.682] RAGENativeUI Examples: Exception message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
> [1/31/2023 10:29:56 PM.683] RAGENativeUI Examples: ------------------------------
> [1/31/2023 10:29:56 PM.683] RAGENativeUI Examples: Inner exceptions:
> [1/31/2023 10:29:56 PM.685] RAGENativeUI Examples: ------------------------------
> [1/31/2023 10:29:56 PM.685] RAGENativeUI Examples: Stack trace:
> [1/31/2023 10:29:56 PM.686] RAGENativeUI Examples: at Rage.Native.NativeFunction.CallByAddress(IntPtr address, Type returnType, NativeArgument[] arguments)
> [1/31/2023 10:29:56 PM.686] at Rage.Native.DynamicNativeFunction.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
> [1/31/2023 10:29:56 PM.687] at CallSite.Target(Closure , CallSite , Object , String , String )
> [1/31/2023 10:29:56 PM.687] at RAGENativeUI.N.GetTextureResolution(String textureDict, String textureName)
> [1/31/2023 10:29:56 PM.688] at RAGENativeUI.PauseMenu.MissionLogo.get_Resolution()
> [1/31/2023 10:29:56 PM.689] at RAGENativeUI.PauseMenu.MissionLogo.get_IsTextureLoaded()
> [1/31/2023 10:29:56 PM.689] at RAGENativeUI.PauseMenu.TabMissionSelectItem.Draw()
> [1/31/2023 10:29:56 PM.689] at RAGENativeUI.PauseMenu.TabView.Update()
> [1/31/2023 10:29:56 PM.690] at RNUIExamples.PauseMenuExample.ProcessMenus()
> [1/31/2023 10:29:56 PM.691] at Rage.GameFiber.Main()
> [1/31/2023 10:29:56 PM.691] RAGENativeUI Examples: ==============================
> ```
